package com.example.psk_lab.mybatis.dao;

import com.example.psk_lab.mybatis.model.Groups;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface GroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    int insert(Groups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    Groups selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    List<Groups> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    int updateByPrimaryKey(Groups record);
}