package com.example.psk_lab.mybatis.dao;

import com.example.psk_lab.mybatis.model.OptionalCourses;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface OptionalCoursesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSES
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSES
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    int insert(OptionalCourses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSES
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    OptionalCourses selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSES
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    List<OptionalCourses> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OPTIONALCOURSES
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    int updateByPrimaryKey(OptionalCourses record);
}