package com.example.psk_lab.mybatis.model;

public class Groups {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUPS.ID
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUPS.COURSE
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    private Integer course;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUPS.DIRECTION
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    private String direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUPS.ID
     *
     * @return the value of PUBLIC.GROUPS.ID
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUPS.ID
     *
     * @param id the value for PUBLIC.GROUPS.ID
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUPS.COURSE
     *
     * @return the value of PUBLIC.GROUPS.COURSE
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    public Integer getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUPS.COURSE
     *
     * @param course the value for PUBLIC.GROUPS.COURSE
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    public void setCourse(Integer course) {
        this.course = course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUPS.DIRECTION
     *
     * @return the value of PUBLIC.GROUPS.DIRECTION
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUPS.DIRECTION
     *
     * @param direction the value for PUBLIC.GROUPS.DIRECTION
     *
     * @mbg.generated Mon Apr 24 03:05:35 EEST 2023
     */
    public void setDirection(String direction) {
        this.direction = direction;
    }
}