package com.example.psk_lab.mybatis.model;

public class OptionalCourses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OPTIONALCOURSES.ID
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OPTIONALCOURSES.NAME
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OPTIONALCOURSES.ID
     *
     * @return the value of PUBLIC.OPTIONALCOURSES.ID
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OPTIONALCOURSES.ID
     *
     * @param id the value for PUBLIC.OPTIONALCOURSES.ID
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OPTIONALCOURSES.NAME
     *
     * @return the value of PUBLIC.OPTIONALCOURSES.NAME
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OPTIONALCOURSES.NAME
     *
     * @param name the value for PUBLIC.OPTIONALCOURSES.NAME
     *
     * @mbg.generated Mon Apr 24 09:29:26 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }
}